app/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import login_view, logout_view, register_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schedules.urls')),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    # path('user/<str:username>/'),
    path('logout/', logout_view, name='logout'),
]

schedules/urls.py
from django.urls import path
from schedules import views


urlpatterns = [
    path('', views.home, name='home'),
    path('appointments/', views.AppointmentListView.as_view(), name='appointments-list'),
    path('appointments/new/', views.AppointmentCreateView.as_view(), name='appointments-create'),
    path('users/<str:username>/appointments/', views.UserAppointmentsListView.as_view(), name='user-appointments-list'),
    path('appointments/sucess/', views.sucess_message, name='sucess'),
    path('appointments/<int:pk>/update/', views.AppointmentUpdateView.as_view(), name='appointment-update'),
    path('appointments/<int:pk>/delete/', views.AppointmentDeleteView.as_view(), name='appointment-delete'),
    path('get_available_times/', views.get_available_times, name='get_available_times'),
]

schedules/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta


class Time(models.Model):
    hours = models.CharField(max_length=20)

    def __str__(self):
        return self.hours


class Appointment(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    day = models.DateField()
    time = models.ForeignKey(Time, on_delete=models.PROTECT, related_name='appointment')
    date_created = models.DateTimeField(auto_now_add=True)
    repeat = models.BooleanField(default=False)

    class Meta:
        unique_together = ('day', 'time')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.repeat:
            for c in range(1, 9):
                new_day = self.day + timedelta(weeks=c)
                Appointment.objects.create(
                    user=self.user,
                    day=new_day,
                    time=self.time,
                    repeat=False,
                )

    def __str__(self):
        return f"{self.user.username} | day: {self.day} | time: {self.time}"

schedules/forms.py
from django import forms
from .models import Appointment, Time
from datetime import datetime


class AppointmentForm(forms.ModelForm):
    time = forms.ModelChoiceField(
        queryset=Time.objects.all(),
        widget=forms.RadioSelect,
        required=True,
        label="Horários",
    )

    class Meta:
        model = Appointment
        fields = ['day', 'time', 'repeat', ]
        widgets = {
            'day': forms.DateInput(attrs={'type': 'date'},),
            'repeat': forms.CheckboxInput(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'day' in self.data:
            try:
                day = self.data.get('day')
                if day:
                    day = datetime.strptime(day, '%Y-%m-%d').date()
                    self.fields['time'].queryset = Time.objects.exclude(
                        id__in=Appointment.objects.filter(day=day).values_list('time_id', flat=True)
                    )
            except (ValueError, TypeError):
                pass
        else:
            self.fields['time'].queryset = Time.objects.all()

schedules/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.shortcuts import render
from django.utils import timezone
from django.http import JsonResponse
from schedules.models import Appointment, Time
from .forms import AppointmentForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import UserPassesTestMixin


def home(request):
    return render(request, 'schedules/home.html')


def sucess_message(request):
    return render(request, 'schedules/sucess.html')


class AppointmentListView(UserPassesTestMixin, ListView):
    model = Appointment
    template_name = 'schedules/appointments_list.html'
    context_object_name = 'appointments'

    login_url = '/login/'
    redirect_field_name = 'redirect_to'

    def test_func(self):
        return self.request.user.is_superuser

    def get_queryset(self):
        today = timezone.localdate()
        return Appointment.objects.filter(day=today)


@method_decorator(login_required(login_url='login'), name='dispatch')
class AppointmentCreateView(CreateView):
    model = Appointment
    form_class = AppointmentForm
    template_name = 'schedules/new_appointment.html'
    success_url = reverse_lazy('sucess')

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        if self.request.method == 'GET' and 'day' in self.request.GET:
            form.fields['time'].queryset = Time.objects.exclude(
                id__in=Appointment.objects.filter(day=self.request.GET['day']).values_list('time_id', flat=True)
            )
        return form

    def form_valid(self, form):
        print("Form is valid. Data:", form.cleaned_data)
        form.instance.user = self.request.user
        response = super().form_valid(form)
        print("Appointment instance:", form.instance)
        return response

    def form_invalid(self, form):
        # Debug: Displaying form errors
        print("Dados submetidos:", self.request.POST)
        print("Erros no formulário:", form.errors)
        return super().form_invalid(form)


@method_decorator(login_required(login_url='login'), name='dispatch')
class UserAppointmentsListView(ListView):
    model = Appointment
    template_name = 'schedules/user_appointments_list.html'
    context_object_name = 'appointments'

    def get_queryset(self):
        user = User.objects.get(username=self.kwargs['username'])
        now = timezone.now()
        return Appointment.objects.filter(user=user, day__gte=now).order_by('day', 'time')


class AppointmentUpdateView(UpdateView):
    model = Appointment
    form_class = AppointmentForm
    template_name = 'schedules/appointment_update.html'

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        if self.request.method == 'GET' and 'day' in self.request.GET:
            form.fields['time'].queryset = Time.objects.exclude(
                id__in=Appointment.objects.filter(day=self.request.GET['day']).values_list('time_id', flat=True)
            )
        return form

    def get_success_url(self):
        username = self.request.user.username
        return reverse_lazy('user-appointments-list', kwargs={'username': username})


@method_decorator(login_required(login_url='login'), name='dispatch')
class AppointmentDeleteView(DeleteView):
    model = Appointment
    template_name = 'schedules/appointment_delete.html'

    def get_success_url(self):
        username = self.request.user.username
        return reverse_lazy('user-appointments-list', kwargs={'username': username})


def get_available_times(request):
    selected_date = request.GET.get('date')
    booked_times = Appointment.objects.filter(day=selected_date).values_list('time', flat=True)
    available_times = Time.objects.exclude(id__in=booked_times)

    data = {
        'available_times': [{'id': time.id, 'time': str(time)} for time in available_times]
    }
    return JsonResponse(data)

schedules/templates/schedules/appointment_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <h3 class="display-4">Deletar Agendamento</h3>
        
        <div class="card">
            <div class="card-body"> 
                <p class="card-text">Tem certeza de que deseja excluir este Agendamento?</p>

                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Deletar</button>
                </form>

                <a href="{% url 'appointments-create' %}" class="btn btn-secondary mt-3">Cancelar e Voltar para lista de Agendamentos?</a>
            </div>
        </div>
    </div>
{% endblock %}

schedules/templates/schedules/appointment_update.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="main_title">
        <h2>Editar Agendamento</h2>
    </div>
    <div class="new_appointment_form">
        <form method="post">
            {% csrf_token %}
            <div class="form_day">
                <label for="id_day">Data:</label>
                {{ form.day }}
            </div>
            <div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">
                {% for time in form.time.field.queryset %}
                <input type="checkbox" class="btn-check" id="time_{{time.id}}" name="time" value="{{time.id}}" autocomplete="off">
                <label class="btn btn-outline-secondary" for="time_{{time.id}}">{{ time }}</label>
                {% endfor %}
            </div>
            <div class="form_repeat">
                <label for="id_repeat">Repetir semanalmente:</label>
                {{ form.repeat }}
                <span class="checkmark"></span>
            </label>
            </div>
            <button type="submit" class="btn btn-primary">Agendar</button>
        </form>
    </div>
</div>
{% endblock %}

schedules/templates/schedules/appointments_list.html
{% extends 'base.html' %}

{% block content %}
<div class="title_user_schedules">
    <h2>Agendamentos do Dia:</h2>
</div>
<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Usuário</th>
                <th>Data</th>
                <th>Horário</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for appointment in appointments %}
            <tr>
                <td>{{ appointment.user.username }}</td>
                <td>{{ appointment.day }}</td>
                <td>{{ appointment.time }}</td>
                <td>
                    <a href="{% url 'appointment-update' appointment.id %}" class="btn btn-warning btn-sm">
                      <i class="bi bi-pencil"></i>
                    </a>
                    <a href="{% url 'appointment-delete' appointment.id %}" class="btn btn-danger btn-sm btn-delete">
                      <i class="bi bi-trash"></i>
                    </a>
                  </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

schedules/templates/schedules/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tenda Fitness Beach Club</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="https://kit.fontawesome.com/6bf3458bf5.js" crossorigin="anonymous"></script>
</head>
<body>
    <main>
        <div class="container">
            <div class="logo">
                <img src="{% static 'img/tenda-fitness-450.png' %}" alt="">
            </div>
            <div class="options_home">
                <div class="scheduling_button">
                    <a href="{% url 'appointments-create' %}">
                        <i class="fa-solid fa-calendar-days"></i>
                        <p>Novo Agendamento</p>
                    </a>
                </div>
                <div class="my_account_buttom">
                    <a href="{% url 'login' %}">
                        <i class="fa-solid fa-user"></i>
                        <p>Minhas Reservas</p>
                    </a>

                </div>
            </div>
        </div>
    </main>
    <footer>
        <p>&copy;Tenda Beach Club</p>
    </footer>
</body>
</html>

schedules/templates/schedules/new_appointment.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="main_title">
        <h2>Novo Agendamento</h2>
    </div>
    <div class="new_appointment_form">
        <form method="post">
            {% csrf_token %}
            <div class="form_day">
                <label for="id_day">Data:</label>
                {{ form.day }}
            </div>
            <div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">
                {% for time in form.time.field.queryset %}
                <input type="checkbox" class="btn-check" id="time_{{time.id}}" name="time" value="{{time.id}}" autocomplete="off">
                <label class="btn btn-outline-secondary" for="time_{{time.id}}">{{ time }}</label>
                {% endfor %}
            </div>
            <div class="form_repeat">
                <label for="id_repeat">Repetir semanalmente:</label>
                {{ form.repeat }}
                <span class="checkmark"></span>
            </label>
            </div>
            <button type="submit" class="btn btn-primary">Agendar</button>
        </form>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRkAaKIBbBvpi4BJQpyRG/jcm57Poc/n3rLcmH7Xz" crossorigin="anonymous"></script>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        var dateField = document.getElementById("id_day");
        var timeContainer = document.querySelector(".btn-group");

        dateField.addEventListener("change", function() {
            var selectedDate = this.value;
            fetch(`/get_available_times?date=${selectedDate}`)
                .then(response => response.json())
                .then(data => {
                    // Clear existing time slots
                    timeContainer.innerHTML = "";

                    // Add new available time slots
                    data.available_times.forEach(function(time) {
                        var timeInput = document.createElement("input");
                        timeInput.type = "checkbox";
                        timeInput.className = "btn-check";
                        timeInput.id = `time_${time.id}`;
                        timeInput.name = "time";
                        timeInput.value = time.id;
                        timeInput.autocomplete = "off";

                        var timeLabel = document.createElement("label");
                        timeLabel.className = "btn btn-outline-secondary";
                        timeLabel.htmlFor = `time_${time.id}`;
                        timeLabel.innerText = time.time;

                        timeContainer.appendChild(timeInput);
                        timeContainer.appendChild(timeLabel);
                    });
                });
        });
    });
    </script>
    
{% endblock %}

schedules/templates/schedules/sucess.html
{% extends 'base.html' %}

{% block content %}
  <h2>Agendamento bem-sucedido!</h2>
  <p>Seu agendamento foi realizado com sucesso.</p>
{% endblock %}

schedules/templates/schedules/user_appointments_list.html
{% extends 'base.html' %}

{% block content %}
  <div class="title_user_schedules">
    <h2>Agendamentos de {{ view.kwargs.username }}</h2>
  </div>
  <div class="table-responsive">
    <table class="table table-striped table-bordered">
      <thead class="thead-dark">
        <tr>
          <th>Data</th>
          <th>Horário</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for appointment in appointments %}
        <tr>
          <td>{{ appointment.day }}</td>
          <td>{{ appointment.time }}</td>
          <td>
            <a href="{% url 'appointment-update' appointment.id %}" class="btn btn-warning btn-sm">
              <i class="bi bi-pencil"></i>
            </a>
            <a href="{% url 'appointment-delete' appointment.id %}" class="btn btn-danger btn-sm btn-delete">
              <i class="bi bi-trash"></i>
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

{% endblock %}